# Generated by Django 2.2.12 on 2021-01-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210124_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postnews',
            old_name='posted_by',
            new_name='location',
        ),
        migrations.AddField(
            model_name='postnews',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postnews',
            name='owner',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postnews',
            name='price',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
